export const CACHE_KEYS = {
    GAMES_BATTLES_BY_ID: id => `game:battle:${id}`,
    GAMES_BATTLES_IDS: "game:battle:ids",
    LIVE_BETS: "live_bets",
    BETS_DISABLED: "bets_disabled",
    GAMES_MINES_BY_USER: userID => `game:mines:${userID}`,
    GAMES_MINES_NONCE_BY_USER: userID => `game:mines:nonce:${userID}`,
    GAMES_PLINKO_NONCE_BY_USER: userID => `game:plinko:nonce:${userID}`,
    GAMES_UNBOXING_NONCE_BY_USER: userID => `game:unboxing:nonce:${userID}`,
    GAMES_IRL_NONCE_BY_USER: userID => `game:irl:nonce:${userID}`,
    GAMES_UPGRADER_NONCE_BY_USER: userID => `game:upgrader:nonce:${userID}`,
    UNBOXING_LAST_UNBOXED: "unboxing:lastUnboxed",
    UNBOXING_TOP_UNBOXED: "unboxing:topUnboxed",
    UNBOXING_DELAYED_JOBS: "unboxing:delayedJobs",
    UPGRADER_GAME_BY_USER: userID => `upgrader:game:${userID}`,
};
